version: '3.8'
x-restart-policy: &restart_policy
  restart: unless-stopped
x-env-file: &env_file
  env_file:
    - ./Dockerenv/default.env
    - ./Dockerenv/${NODE_CONFIG_ENV}.env

services:
  postgres:
    image: mdillon/postgis:11
    <<: *restart_policy
    <<: *env_file
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "27188:5432"
    restart: always

  api:
    container_name: scrinity-api
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    <<: *restart_policy
    <<: *env_file
    environment:
      - SERVICE=api
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - WEB_PUSH_PRIVATE=${WEB_PUSH_PRIVATE}
    volumes:
      - ./templates:/app/templates
    ports:
      - "27180:3001"
    depends_on:
      - postgres

  manager:
    container_name: scrinity-manager
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    <<: *restart_policy
    <<: *env_file
    environment:
      - SERVICE=manager
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - WEB_PUSH_PRIVATE=${WEB_PUSH_PRIVATE}
    ports:
      - "27181:3002"
    depends_on:
      - postgres

  aggregator:
    container_name: scrinity-aggregator
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    <<: *restart_policy
    <<: *env_file
    environment:
      - SERVICE=aggregator
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    ports:
      - "27184:3002"
    depends_on:
      - postgres

volumes:
  postgres_data:
