version: '3.6'
x-restart-policy: &restart_policy
  restart: unless-stopped
x-env-file: &env_file
  env_file:
    - ./Dockerenv/default.env
    - ./Dockerenv/${NODE_CONFIG_ENV}.env

services:
  nginx:
    image: 343300559621.dkr.ecr.eu-west-1.amazonaws.com/project-z-nginx
    ports:
      - "80:80"

  postgres:
    image: mdillon/postgis:11
    <<: *restart_policy
    <<: *env_file
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "27188:5432"
    restart: always

  api:
    image: 343300559621.dkr.ecr.eu-west-1.amazonaws.com/project-z:latest
    <<: *restart_policy
    <<: *env_file
    environment:
      - SERVICE=api
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "27180:3001"

volumes:
  postgres_data:
