version: '3.8'
x-restart-policy: &restart_policy
  restart: unless-stopped
x-env-file: &env_file
  env_file:
    - ./Dockerenv/default.env
    - ./Dockerenv/${NODE_CONFIG_ENV}.env

services:
  postgres:
    image: mdillon/postgis:11
    <<: *restart_policy
    <<: *env_file
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "27188:5432"
    restart: always

  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
#    image: 343300559621.dkr.ecr.eu-west-1.amazonaws.com/project-z:latest
    <<: *restart_policy
    <<: *env_file
    environment:
      - SERVICE=api
    volumes:
      - ./templates:/app/templates
    ports:
      - "27180:3001"
    depends_on:
      - postgres

  manager:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
#    image: 343300559621.dkr.ecr.eu-west-1.amazonaws.com/project-z-manager:latest
    <<: *restart_policy
    <<: *env_file
    environment:
      - SERVICE=api
    ports:
      - "27181:3002"
    depends_on:
      - postgres

#  client:
#    image: 343300559621.dkr.ecr.eu-west-1.amazonaws.com/project-z-client
#    ports:
#      - "27182:3000"
#
#  admin:
#    image: 343300559621.dkr.ecr.eu-west-1.amazonaws.com/project-z-admin
#    ports:
#      - "27183:27183"

volumes:
  postgres_data:
