version: '3.8'
x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgres:
    image: mdillon/postgis:11
    <<: *restart_policy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=project-z
    volumes:
      - postgres_data_new:/var/lib/postgresql/data/
    ports:
      - "27188:5432"
    restart: always

  api:
    image: 343300559621.dkr.ecr.eu-west-1.amazonaws.com/project-z:latest
    <<: *restart_policy
    environment:
      - SERVICE=api
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=project-z
    depends_on:
      - postgres
    ports:
      - "27180:3001"

  client:
    image: 343300559621.dkr.ecr.eu-west-1.amazonaws.com/project-z-client
    ports:
      - "27182:3000"

volumes:
  postgres_data_new:
