export enum PLATFORM_AGGREGATORS {
  YANDEX = 'YANDEX',
  GOOGLE = 'GOOGLE',
  RELAX = 'RELAX',
  TRIPADVISOR = 'TRIPADVISOR',
  CARTE = 'CARTE',
  KOKO = 'KOKO',
}

export enum AGGREGATION_TYPE {
  API = 'API',
  PARSER = 'PARSER',
}
