export const INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER';
export const CONFIRM_CODE_INVALID_LENGTH = 'CONFIRM_CODE_INVALID_LENGTH';
export const CODE_NOT_FOUND = 'CODE_NOT_FOUND';
export const REQUEST_CONFIRM_CODE_LIMIT = 'REQUEST_CONFIRM_CODE_LIMIT';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const INVALID_EMAIL = 'INVALID_EMAIL';
export const TOO_LONG_STRING = 'TOO_LONG_STRING';
