export const INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER';
export const CONFIRM_CODE_INVALID_LENGTH = 'CONFIRM_CODE_INVALID_LENGTH';
export const CODE_NOT_FOUND = 'CODE_NOT_FOUND';
export const REQUEST_CONFIRM_CODE_LIMIT = 'REQUEST_CONFIRM_CODE_LIMIT';
export const AUTHORIZATION_COOKIE = 'Authorization';
export const COOKIE_EXPIRES_HOURS = 24;
