export const INVALID_IMAGES_FORMAT = 'INVALID_IMAGES_FORMAT';
export const CRITERIONS_NOT_FOUND = 'CRITERIONS_NOT_FOUND';
export const CHAT_NOT_FOUND = 'CHAT_NOT_FOUND';
export const INACCESSIBLE_CHAT = 'INACCESSIBLE_CHAT';
export const ANONYMOUSLY_CHAT = 'ANONYMOUSLY_CHAT';
