name: build and deploy

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      NODE_CONFIG_ENV: ${GITHUB_REF##*/}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
      WEB_PUSH_PRIVATE: ${{ secrets.WEB_PUSH_PRIVATE }}
      PROXY_HOST: ${{ secrets.PROXY_HOST }}
      PROXY_PORT: ${{ secrets.PROXY_PORT }}
      PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
#      - run: pm2 stop back
      - run: NODE_CONFIG_ENV=${GITHUB_REF##*/} docker-compose up -d --build
#      - run: pm2 start all

