name: build and deploy

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted
    env:
          NODE_CONFIG_ENV: develop
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
      - run: ./node_modules/pm2/bin/pm2 restart all
